server {
    listen 80;
    server_name puzzle.xivnick.me;
    return 301 https://puzzle.xivnick.me$request_uri;
}

server {
    listen 443 ssl;
    server_name puzzle.xivnick.me;
    ssl_certificate /etc/letsencrypt/live/xivnick.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xivnick.me/privkey.pem;

    root /home/xivnick/vodka-puzzle/dist;
    index index.html;
    autoindex off;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\. {
        deny all;
    }
}
